### ISSUE TITLE
Unable to complete / Wo ist die aktuelle Datenbank ?

### ISSUE THREAD

**Issue by MaLa-Q3** [hermes5/websolution#1]
@hermes5 , @mc-b 
Frage: Wer kann mir helfen die richtige Quelle / Ansprechpartner für die Hermes5 Grunddatenbank zu finden? Möchte gerne eine eigene Instanz für BLS AG einrichten. 
Link zum Download ist entfernt worden, .... ??
:smirk:

Datenbank
Die HERMES Web Awenderlösung benötigt für deren Funktion einen Grunddatenbank. Diese ist von **...** downzuladen und in die MySQL Datenbank zu importieren.

**Comment by mc-b** [comment]
Hallo,

bitte Mail an marcel.bernet@ch-open.ch mit Verwendungszweck senden.

Der Link zur Datenbank folgt dann in 2 - 3 Arbeitstagen.

freundliche Grüsse
